definitions:
  notifications_api.errorResponse:
    properties:
      error:
        type: string
    type: object
  notifications_api.notificationsRequest:
    properties:
      message:
        type: string
      recipient:
        type: string
    required:
    - message
    - recipient
    type: object
  notifications_api.notificationsResponse:
    properties:
      id:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /notifications:
    post:
      consumes:
      - application/json
      description: Создает новое уведомление для указанного получателя
      parameters:
      - description: Notification payload
        in: body
        name: notification
        required: true
        schema:
          $ref: '#/definitions/notifications_api.notificationsRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/notifications_api.notificationsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/notifications_api.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/notifications_api.errorResponse'
      summary: Создать уведомление
      tags:
      - notifications
swagger: "2.0"
